### DISCUSSION TITLE
Github actions skipping PR Comment

### DISCUSSION THREAD

**Discussion by theonlydola** [LironEr/bundlemon#215] [Q&A] [answered]
I followed the [github actions guide](https://github.com/LironEr/bundlemon-github-actions) 
I'm using bundlemon github APP, Everything runs correctly however, it never posts the PR comment instead it shows this message.

<img width="766" alt="Screenshot 2024-10-01 at 1 59 44 PM" src="https://github.com/user-attachments/assets/8202beee-979c-4754-8cc5-d851dbf9108e">

This is `reportOutput` in `.bundlemonrc.json`

`"reportOutput": [
    [
      "github",
      {
        "checkRun": true,
        "commitStatus": true,
        "prComment": "always"
      }
    ]
  ]`
  
  
  Any idea what is going wrong? Why it doesn't detect a PR?

**Comment by theonlydola** [comment]
@LironEr Sorry for bothering. but, any thoughts?

**Comment by LironEr** [comment]
Sorry, I'm on vacation and don't have my computer with me for a few days.

In the meantime you can set "verbose" option to true and add all the logs here, that would help to identify the issue.

In case there is a sensitive data in the logs you can reduct it and add here, If you prefer you can also send the logs to my email lironerm@gmail.com

Also please add the bundlemon version, config file and the github workflow file. 

Thanks.

**Reply by theonlydola** [reply]
Hello, 
Thank you for replying back, Apologies I have just seen it.

Package Version: `"bundlemon": "^3.0.3"`

Config File:

![Screenshot 2024-10-17 at 6 23 13 PM](https://github.com/user-attachments/assets/e6caf760-dc1f-420c-b429-846d972160a3)


We have a bigger workflow file for PR Checks and we added this step to it.

![Screenshot 2024-10-17 at 6 24 24 PM](https://github.com/user-attachments/assets/3f8e6cb1-ab8e-42f2-af67-0dc87838dac3)


I added `verbose` and noticed these

<img width="555" alt="Screenshot 2024-10-17 at 6 25 50 PM" src="https://github.com/user-attachments/assets/bf436bde-0682-4c2b-b1d9-84f4c416ca78">
<img width="856" alt="Screenshot 2024-10-17 at 6 26 28 PM" src="https://github.com/user-attachments/assets/706fd67b-31d3-4e91-ae58-f466c7a9aa9d">


Thank you again!

**Comment by LironEr** [comment]
I think there might be an issue with how it [detects a PR](https://github.com/LironEr/bundlemon/blob/main/packages/bundlemon/lib/main/utils/ci/providers/github.ts#L26)

Upgrade to bundlemon [v3.1.0](https://github.com/LironEr/bundlemon/releases/tag/bundlemon%40v3.1.0) and run again.
I added more logs to the "CI vars" print.
Please attach the new logs and the triggers section of the workflow that runs BundleMon. hopefully then, I can understand what is wrong.

Thanks.

**Reply by theonlydola** [reply]
I will and get back to you. However, Don't you think it might be how you get the [PR Number](https://github.com/LironEr/bundlemon/blob/588954661d2665695e49f07804cb5bdef429132d/packages/bundlemon/lib/main/utils/ci/providers/github.ts#L38)? 

If you check my screenshot you will find all CI Vars are there but, not the PR number.

**Reply by LironEr** [reply]
Yeah, that is also a possibility.

So we need to check both options:
1. bad `isPr` variable (`GITHUB_EVENT_NAME` env var)
2. Bad parsing of `GITHUB_REF` env var

Anyway, the logs should help with that

**Reply by theonlydola** [reply]
Ok, I updated to `v3.1.0` and now it shows that permission denied there is no `CI_COMMIT_SHA` I tried setting it manually and it's still showing the error.

<img width="605" alt="Screenshot 2024-10-20 at 6 01 37 PM" src="https://github.com/user-attachments/assets/6a050172-9092-444d-9036-eb9a1a7baeba">

**Reply by theonlydola** [reply]
Hello @LironEr, Any updates about this?

**Reply by LironEr** [reply, marked as answer]
That's weird, I never encountered permissions denied error with bundlemon, I'm also [running the action every 1 hour](https://github.com/LironEr/bundlemon-monitor-workflow) to verify the service is working and didn't have a problem with that.

You can try to use BundleMon directly without the action, like [here](https://github.com/LironEr/bundlemon/blob/main/.github/workflows/build-web.yml#L27)

```yaml
- name: Run bundlemon
  run: npx bundlemon
  env:
    CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
    CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
```

Add `CI_TARGET_BRANCH` and `CI_PR_NUMBER` to env vars like you did before.

Please add the full workflow with the triggers section, might find how to fix that in BundleMon without overriding the env vars.

**Reply by okize** [reply]
@LironEr we started getting `bundlemon: Permission denied` errors around 9AM EST on October 23rd. this coincided with an upgrade to `bundlemon` `v3.1.0` so we tried downgrading but got the same results with `v3.0.3`

it's unfortunately a private github repo so i can't share but this is the output from a branch using `bundlemon` `v3.1.0`:

```
Run lironer/bundlemon-action@v1.2.0
  with:
    bundlemon-args: --config bundlemon.vhs.mjs --subProject "vhs-package"
  env:
    TOOL_VERSION_NODEJS: [2](https://github.com/wistia/vhs/actions/runs/11517470244/job/32062213309?pr=2069#step:6:2)0.18.0
    TOOL_VERSION_YARN: 1.22.19
set environment vars for BundleMon CLI
set env variable: CI_COMMIT_SHA
Running: npx bundlemon --config bundlemon.vhs.mjs --subProject vhs-package
/opt/hostedtoolcache/node/20.18.0/x6[4](https://github.com/wistia/vhs/actions/runs/11517470244/job/32062213309?pr=2069#step:6:4)/bin/npx bundlemon --config bundlemon.vhs.mjs --subProject vhs-package
sh: 1: bundlemon: Permission denied

sh: 1: bundlemon: Permission denied
```

FWIW, running `bundlemon` outside of CI works without issue
