### ISSUE TITLE
Integration help - Vite

### ISSUE THREAD

**Issue by dominicaw** [LironEr/bundlemon#204]
Hi!
Firstly, thank you for making this tool, it seems great :)
I'm just currently having trouble getting the integration working as expected. Currently, Bundlemon does not seem to be saving the history of my repo's main branch. Every PR lists the files as 'added', and doesn't seem to compare them to the main branch files.

I'm using Vite 5 for my project, and I have the following in my `.bundlemonrc.json`:

```
{
  "baseDir": "./build",
  "files": [
    {
      "path": "index.html"
    },
    {
      "path": "assets/*-<hash>.js",
      "maxPercentIncrease": 10
    }
  ],
  "reportOutput": [
    [
      "github",
      {
        "checkRun": true,
        "commitStatus": false,
        "prComment": true
      }
    ]
  ]
}
```

My build files look like so:
![Screenshot 2024-05-20 at 16 49 27](https://github.com/LironEr/bundlemon/assets/43538692/d79fc377-ba00-4d6b-842e-84b2f8dafb40)

In my Github action yml, I have simply added this as a step in an existing job:

```
- name: Analyse Bundle Size
   uses: lironer/bundlemon-action@v1
```

However, with this, the Bundlemon comments that the files are new on each PR
![Screenshot 2024-05-20 at 16 51 57](https://github.com/LironEr/bundlemon/assets/43538692/a8f108a2-7da2-4425-b608-c4fb75e0687c)
![Screenshot 2024-05-20 at 16 52 08](https://github.com/LironEr/bundlemon/assets/43538692/450f376a-42ea-4fcc-ac32-985efeae2346)

Not sure what exactly I am doing wrong?

**Comment by LironEr** [comment]
Hey (:

BundleMon needs to run on your main branch on every commit so it can create a baseline, your workflow triggers should look like this:

```yml
on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]
```

Let me know if it helped, or if it was already like this please add the full workflow.

Also, not related to the original question but still worth mentioning, As vite creates hash with letters, numbers, `-` and `_` I recommend using [`pathLabels` ](https://github.com/LironEr/bundlemon/blob/master/docs/customPathLabels.md)

```json
"pathLabels": {
    "hash": "[a-zA-Z0-9\\-_]+"
}
```

I am also in the process of upgrading this bundlemon website to Vite, so you can take a look [here](https://github.com/LironEr/bundlemon/blob/e047120b5030923a624438a9f668382cc5aca46f/apps/website/.bundlemonrc.json#L25)

**Comment by dominicaw** [comment]
Thanks for the response @LironEr :)
Ok so, I have two workflows on my repo - one for PRs, and another for main, when PRs are released. So I need to have the bundlemon action on both of these workflows?

So to be more explicit: 
The workflow for PRs `main.yml`:

```
name: Main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-and-code-quality:
    name: Tests and Code Quality
    timeout-minutes: 40
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout full history for a better relevancy of analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run Unit Tests
        run: npm run ci:unit-tests:run

      - name: Run Acceptance Tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run ci:acceptance-tests:start
          config: specPattern=cypress/integration/*.{feature,features}
          wait-on: xxxx

      - name: Analyse Bundle Size
        uses: lironer/bundlemon-action@v1

      - name: Merge Coverage Reports
        run: npm run test:merge-coverage-reports

      - name: Upload Code Coverage Report for next workflow(s)
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage--merged

      - name: Code Quality Scan
        uses: SonarSource/sonarcloud-github-action@master
```

The workflow to main branch, `release.yml`:

```
name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"

jobs:
  release:
    name: Release
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout full history for a better relevancy of analysis
          token: ${{ secrets.PAT_RELEASE_MANAGEMENT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
  
      - name: Install dependencies
        run: yarn install

      - name: Run Build
        run: CI=false yarn run build

      - name: Download Code Coverage Report from previously run workflow
        id: download-code-coverage-report
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          name: code-coverage-report
          path: coverage--merged
          if_no_artifact_found: fail

      - name: Conventional Changelog
        id: conventionalchangelog
        uses: TriPSs/conventional-changelog-action@v3

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: https://sentry.io/
        with:
          environment: production
          version: ${{ steps.conventionalchangelog.outputs.tag }}
          sourcemaps: xxx

      - name: Code Quality Scan
        uses: SonarSource/sonarcloud-github-action@master
```

So I need to add Bundlemon action in `release.yml` ?
